input {
  jdbc {
    jdbc_driver_library => "/Users/wedalotibi/RASD_adaptive-api-deception/logstash/drivers/sqlite-jdbc.jar"
    jdbc_driver_class => "org.sqlite.JDBC"
    jdbc_connection_string => "jdbc:sqlite:/Users/wedalotibi/RASD_adaptive-api-deception/proxy_logs.db"
    jdbc_user => ""
    jdbc_password => ""

    schedule => "* * * * *"

    statement => "
  SELECT
    id,
    request_id,
    timestamp,
    client_ip,
    method,
    path,
    path AS endpoint,
    query_params,
    headers,
    body,
    response_status,
    response_status AS status,
    response_time_ms,
    response_time_ms AS response_time,
    forwarded_to_backend,
    backend_error,
    flagged_as_suspicious,
    suspicion_reason,
    session_id,
    anomaly_score,
    routed_to,
    created_at
  FROM proxy_requests
  WHERE id > :sql_last_value
  ORDER BY id ASC
"

    use_column_value => true
    tracking_column => "id"
    tracking_column_type => "numeric"
    last_run_metadata_path => "/Users/wedalotibi/RASD_adaptive-api-deception/logstash/.logstash_jdbc_last_run"
    clean_run => true
  }
}

filter {
  mutate {
    convert => {
      "id" => "integer"
      "status" => "integer"
      "response_status" => "integer"
      "response_time" => "integer"
      "response_time_ms" => "integer"
      "forwarded_to_backend" => "boolean"
      "flagged_as_suspicious" => "boolean"
      "anomaly_score" => "float"
    }
  }



 date {
  match => ["created_at", "ISO8601"]
  target => "@timestamp"
}
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "rasd-api-logs"
  }
  stdout { codec => rubydebug }
}