input {
  file {
    path => "/Users/wedalotibi/RASD_adaptive-api-deception2/data/proxy.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}


filter {
  if [message] =~ "HTTP Request:" {
    drop { }
  }
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} \[proxy\] id=%{UUID:request_id} %{WORD:method} %{URIPATHPARAM:endpoint} -> %{NUMBER:status} %{NUMBER:response_time}ms"
    }
  }

  mutate {
    convert => {
      "status" => "integer"
      "response_time" => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "rasd-api-logs"
  }
   stdout { codec => rubydebug }
}